### ISSUE TITLE
Please show the cursor in dialog boxes

### ISSUE THREAD

**Issue by DidierSpaier** [sbopkg/sbopkg#10]
Hi,

It would help blind users to be able to "see" where the cursor is positioned in a list, i.e. which item is highlighted on a screen, but not on a Braille terminal. Just using the "--visit-items" option of dialog does the trick: I ended up including it in the  Slint installers and that works.

This would help blind users to select the proper item.

TIA,
Didier

**Comment by willysr** [comment]
please confirm with this commit: 157dce9f9070cc1929c1f6e897f4f5542a4a4d5a

**Comment by DidierSpaier** [comment]
Confirmed.
