### ISSUE TITLE
Change _SBo -> _sbopkg

### ISSUE THREAD

**Issue by willysr** [sbopkg/sbopkg#11]
As per SBo policy [1] we need to change _SBo into other tag and we choose _sbopkg

Unfortunately, it's not simply renaming tags in the repos.d/ but the code must also support old tags so that packages installed on user's machine will still showed up. Otherwise, users will have to rebuild everything to see their packages showed up in the sbopkg.

[1] http://slackbuilds.org/faq/#package_repos

**Comment by j12i** [comment]
How is sbopkg "provid[ing] a public repository of precompiled packages"?
Was this discussed on SlackBuilds-users or somewhere?

**Comment by willysr** [comment]
No, this is not what sbopkg is intended to.
You can use SlackOnly: http://packages.slackonly.com/pub/packages/

**Comment by j12i** [comment]
No no, I just don't see why the tag change is neccessary..

**Comment by willysr** [comment]
Actually it's needed due to the SBo policy
See https://slackbuilds.org/faq/#package_repos

**Comment by willysr** [comment]
after some considerations, i decided to drop this as it requires lots of efforts with minimum effect on the gain
