### ISSUE TITLE
hamachi-2.1.0.139-x86_64-1_SBo

### ISSUE THREAD

**Issue by ryotov** [sbopkg/sbopkg#14]
Hi,

As i needed a newer version of logmein-hamachi changed the build to download & install the last one.
The diff is below:
diff -u src/builds/hamachi/hamachi.SlackBuild work/hamachi.SlackBuild 
--- src/builds/hamachi/hamachi.SlackBuild       2015-10-24 17:10:09.600204658 +0300
+++ work/hamachi.SlackBuild     2013-11-26 11:57:40.000000000 +0200
@@ -6,7 +6,7 @@
 
 PRGNAM=hamachi
 SRCPKGNAM=logmein-$PRGNAM
-VERSION=${VERSION:-2.1.0.139}
+VERSION=${VERSION:-2.0.1.13}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
...
Then build the new version and it's running for some weeks now.
The code is downloaded from their site.

Thanks,
Rumen

**Comment by willysr** [comment]
This should be addressed in SBo maintainers, not sbopkg.
