### ISSUE TITLE
Feature request: possibility to install an old version of a software

### ISSUE THREAD

**Issue by griebd** [sbopkg/sbopkg#16]
Firstly, thanks for the great tool!
And then, the request, is it possible to install an old version of a software?
I just got in a situation where the latest version of a library available in SlackBuilds.org is incompatible with something I need it for... I just went to http://slackbuilds.org/cgit/ and got the older scripts there, just editing the .SlackBuild file wasn't enough because there were patches applied.
If you use git to get the scripts, I think it shouldn't be so much of a job to add support for older versions. If not.... :wink:

**Comment by willysr** [comment]
I'm afraid i can't grant your request
sbopkg is just a tool to help you install packages that comes from SBo repository, so it will use what's available from the SBo repository itself.

**Comment by griebd** [comment]
well, technically speaking, the old versions ARE on the SBo repository! you just need to access them through git...
but I understand the situation, it's something rarely need and not simple to implement if you are not using git already.
no worries. and again, thanks for sbopkg!!!
