### ISSUE TITLE
Add checksums and signing key to verify sbopkg archive

### ISSUE THREAD

**Issue by BrentonEarl** [sbopkg/sbopkg#18]
It would be excellent if the download page on sbopkg.org had both MD5 and SHA256 check sums to verify the file integrity of the sbopkg Slackware package.  If possible a PGP signing key as well.

Many Slackware users use sbopkg as a package manager.  It is important that the file integrity of the packaged binary be verified.

Thanks!

**Comment by willysr** [comment]
Done for MD5 and SHA1
SHA256 will be too long to display
