### ISSUE TITLE
False GPG failure for letsencrypt slackbuild

### ISSUE THREAD

**Issue by ChrisAbela** [sbopkg/sbopkg#19]
Maybe because there is also a letsencrypt.sh slackbuild

**Comment by willysr** [comment]
confirmed

**Comment by willysr** [comment]
@ChrisAbela can you test the fix i committed (https://github.com/sbopkg/sbopkg/commit/4e9d6c8b3069238eea3f3b62eb2c350f9075edc6) in the separate branch?

**Comment by ChrisAbela** [comment]
We're almost there. Try this:

# diff -u sbopkg sbopkg.new 
--- sbopkg      2016-08-30 08:53:01.514939351 +0200
+++ sbopkg.new  2016-08-30 08:51:40.963143382 +0200
@@ -1415,7 +1415,7 @@
             $GPGNAME tarball found.")" 8 40
         return 1
     fi
-    if ! gpg --verify $CHKPKG.*.asc > /dev/null 2>&1; then
+    if ! gpg --verify $CHKPKG.tar.gz.asc > /dev/null 2>&1; then
         dialog --title "WARNING" --yesno "$(crunch "GPG CHECK FAILED!\n\n \
             Would you like to delete the $GPGNAME directory and tarball \
             so you can perform a new sync?  If so, all local changes to \

**Comment by willysr** [comment]
OK, it should be better now
https://github.com/sbopkg/sbopkg/compare/fix-gpg-failure

**Comment by willysr** [comment]
merged to master.

closing this issue and thanks for reporting.
