### ISSUE TITLE
rsync & git are inconsistent

### ISSUE THREAD

**Issue by swmarc** [sbopkg/sbopkg#30]
If using rsync for a repository, it creates the Slackware version as directory under /var/lib/sbopkg/SBo and places all SlackBuilds within there. If using git for a repository, all SlackBuilds are placed directly under /var/lib/sbopkg/SBo without a version as directory.

This (at least) breaks `sqg` in the master branch.

**Comment by willysr** [comment]
Using git master meaning that it evolves over time, so it doesn't require any spesific directory, while stable repo are used to differentiate which branch you are using.

during development of 14.2, i switch to master branch since submission is closed and i can still use sqg. I wonder what breakage do you experienced?

is it because of 1eb39ee8ebbf8387b45bade396b6de5daa74da4a ?

**Comment by swmarc** [comment]
It isn't about master because you can use any branch with with git in 40-sbo.repo.

cat /etc/sbopkg/repos.d/40-sbo.repo
SBo 14.2 "SBo repository for Slackware 14.2" _SBo git git://slackbuilds.org/slackbuilds.git@14.2 ""
SBo 14.1 "SBo repository for Slackware 14.1" _SBo rsync slackbuilds.org::slackbuilds/14.1 GPG
SBo 14.0 "SBo repository for Slackware 14.0" _SBo rsync slackbuilds.org::slackbuilds/14.0 GPG
...

**Comment by swmarc** [comment]
And yes, it may broke with commit 1eb39ee, but before fixing it, I'd like to know how we need to behave.
I'd like to see a version directory also for git.

**Comment by willysr** [comment]
try to use 90-SBo-master.repo
it works fine here

**Comment by willysr** [comment]
in /etc/sbopkg/sbopkg.conf
change
`REPO_BRANCH=${REPO_BRANCH:-14.2}`
into
REPO_BRANCH=${REPO_BRANCH:-master}

**Comment by swmarc** [comment]
It isn't about master. Please see the first line from my comment above for the branch 14.2. I've changed it from `rsync` to `git` in 40-sbo.repo.

**Comment by willysr** [comment]
i tested with your configuration and sqg still works here

**Comment by willysr** [comment]
```
sqg -a
Processing all SlackBuilds in the SBo repository...Done.
```

```
ls /var/lib/sbopkg/queues/ | wc -l
2812
```

```
sbopkg -i gradle
Both a queuefile and a package were found with the name "gradle".

Use (Q)ueuefile, (P)ackage, or (A)bort?: q

###########################################
       New queue process started on:
       Wed Apr 12 19:28:54 WIB 2017
###########################################

+++++++++++++++++++++++++++++++++++++++++++
PRE-CHECK LOG
Using the SBo repository for Slackware 14.2
Queue Process:  Download, build, and install

jdk:
  GPG checks not supported for the SBo repository.
  Processing jdk 8u121-1
  Using original .info file
  Using original SlackBuild file
  No build options selected.

gradle:
  GPG checks not supported for the SBo repository.
  Processing gradle 3.1-1
  Using original .info file
  Using original SlackBuild file
  No build options selected.

+++++++++++++++++++++++++++++++++++++++++++

Pre-check complete.

Do you wish to proceed based on the search results above? Packages not
found will be skipped during the process.
```

**Comment by swmarc** [comment]
Maybe this is more clear:

Using the 14.2 with git
> sbopkg -r
> Checking out files: 100% (32577/32577), done.
> Syncing with the remote repository into /var/lib/sbopkg/SBo.
> From git://slackbuilds.org/slackbuilds
> * branch            14.2       -> FETCH_HEAD
> Already up-to-date.
> HEAD is now at 41beac5 Public www update: Sat Apr  8 01:46:04 UTC 2017.
>
> Repository update complete.
>
> ls /var/lib/sbopkg/SBo 
> ChangeLog.txt  academic/       audio/     desktop/      games/  graphics/  haskell/    misc/        network/  perl/    ruby/
> README         accessibility/  business/  development/  gis/    ham/       libraries/  multimedia/  office/   python/  system/

Directly using 14.2 afterwards with rsync
> Rsync with the SBo repository for Slackware 14.2 complete.
>
> Importing SBo repository for Slackware 14.2 GPG Key...
> Import done.
>
> ***SYNC COMPLETE***
> ls /var/lib/sbopkg/SBo 
> 14.2/          academic/       business/     games/     ham/        misc/        office/  ruby/
> ChangeLog.txt  accessibility/  desktop/      gis/       haskell/    multimedia/  perl/    system/
> README         audio/          development/  graphics/  libraries/  network/     python/

See the 14.2/ directory and the other directories which are also from the 14.2 branch, but gotten by git.

**Comment by willysr** [comment]
that's the effect of mixing between rsync and git because both have it's own of handling.

see https://github.com/sbopkg/sbopkg/blob/master/src/usr/sbin/sbopkg#L2421 and https://github.com/sbopkg/sbopkg/blob/master/src/usr/sbin/sbopkg#L1006

**Comment by swmarc** [comment]
That's clear, but sbopkg is supporting git also for other branches than master and I personally favor git over rsync, just because it's a lot faster.
My mind is, that it is broken instead of just calling it an "effect of mixing", because that way you can't have many branches with git. Also, you would need to support 2 different directory structures just for the master branch.

**Comment by swmarc** [comment]
Supplement: `sqg` is actually broken if using `rsync` for synchronizing branches.

**Comment by willysr** [comment]
tested with rsync and git here and it just works

did you use 0.38.1 or master branch of sbopkg ?
i'm using 0.38.2 (an internal build from latest master branch of sbopkg)

**Comment by swmarc** [comment]
Yes, I'm using the version from master.
Here's my output after synchronizing with rsync (14.2):

> sqg -a
> Processing all SlackBuilds in the SBo repository...
> Computers / CPU cores / Max jobs to run
> 1:local / 8 / 1
> 
> Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
> ETA: 0s Left: 6514 AVG: 0.00s  local:1/0/100%/0.0s geoserver-pyramid: not found.
> /usr/libexec/sbopkg/sqg/functions: line 124: [: missing `]'
> /usr/libexec/sbopkg/sqg/functions: line 124: y)$: command not found
> ETA: 0s Left: 6513 AVG: 0.00s  local:1/1/100%/1.0s osgEarth: not found.
> /usr/libexec/sbopkg/sqg/functions: line 124: [: missing `]'
> /usr/libexec/sbopkg/sqg/functions: line 124: y)$: command not found
> ETA: 0s Left: 6512 AVG: 0.00s  local:1/2/100%/0.5s geoserver: not found.
> ...

**Comment by swmarc** [comment]
But line 124 is a bug itself, as it wouldn't run with git either if a file is not found.

**Comment by willysr** [comment]
here's the output on my VM

```
sqg -a
Processing all SlackBuilds in the SBo repository...
Computers / CPU cores / Max jobs to run
1:local / 1 / 1

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
ETA: 0s Left: 0 AVG: 0.04s  local:0/13028/100%/0.0s      
Done.
```

here's my 40-sbo.repo
`SBo 14.2 "SBo repository for Slackware 14.2" _SBo rsync slackbuilds.org::slackbuilds/14.2 GPG`

**Comment by swmarc** [comment]
Did you clear your /var/lib/sbopkg/SBo directory before? 13028 items seems to be the doubled amount of SlackBuilds.

**Comment by willysr** [comment]
i removed /var/lib/sbopkg/queues, not /var/lib/sbopkg/SBo

**Comment by willysr** [comment]
```
ls /var/lib/sbopkg/queues/ | wc -l
2812
```

**Comment by swmarc** [comment]
Clear /var/lib/sbopkg/SBo and do a clean rsync on one branch. It could be that you also have a mix up now of git & rsync files.

**Comment by willysr** [comment]
```
sent 893,898 bytes  received 92,186,272 bytes  94,258.40 bytes/sec
total size is 88,946,562  speedup is 0.96

Rsync with the SBo repository for Slackware 14.2 complete.

Importing SBo repository for Slackware 14.2 GPG Key...
Import done.

***SYNC COMPLETE***

sqg -a
Processing all SlackBuilds in the SBo/14.2 repository...
Computers / CPU cores / Max jobs to run
1:local / 1 / 1

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
ETA: 0s Left: 0 AVG: 0.04s  local:0/6514/100%/0.0s      
Done.
```

**Comment by swmarc** [comment]
Really weird. I can reproduce mine on 3 different workstations. Same latest master version.
Beside that, is it open for discussion anyway, having sub-directories also for git checkouts?

**Comment by willysr** [comment]
Try this: http://sbopkg.org/test/sbopkg-0.38.2-noarch-1_wsr.tgz

**Comment by willysr** [comment]
I'll close this for now, please reopen if needed

closing #30
