### ISSUE TITLE
sqg: Parallelize building of queue files in conjunction with option -p

### ISSUE THREAD

**Issue by swmarc** [sbopkg/sbopkg#32]
With a rather large list of packages the option -p would also benefit of parallelization with option -j.

**Comment by willysr** [comment]
I have no objection with this feature, but only a small number of scripts that has large list of deps and running for a single script with -p usually takes less then 5s in normal hardware, and probably less in modern hardware.

**Comment by swmarc** [comment]
Great, so I'd start a pull request.

But by the way, dependency resolution isn't parallelized, but each single SlackBuild.
I've found out that a couple of SlackBuilds are taking multiple seconds to proceed.
So having a rather large amount of SlackBuilds with option -p could lead to seconds 
to proceed instead of just a couple of seconds with the jobs option.

**Comment by swmarc** [comment]
Just for the stats. 25 SlackBuilds with the highest amount of dependencies.

time sqg \
  -p "\
    vlc pandoc darcs plaso flexget haskell-tls shutter dfvfs ClusterSSH \
    letsencrypt conan PAC spamassassin soundconverter haskell-x509-validation \
    haskell-http-client calibre RYMTracks Electrum-DASH salt mythtv \
    mysql-workbench Electrum xmltv virt-manager" \
  -j 1

Computers / CPU cores / Max jobs to run
1:local / 8 / 1

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
ETA: 0s Left: 0 AVG: 1.84s  local:0/25/100%/1.9s   s 
Done.

real	0m53.555s
user	0m17.723s
sys	    0m24.775s

time sqg \
  -p "\
    vlc pandoc darcs plaso flexget haskell-tls shutter dfvfs ClusterSSH \
    letsencrypt conan PAC spamassassin soundconverter haskell-x509-validation \
    haskell-http-client calibre RYMTracks Electrum-DASH salt mythtv \
    mysql-workbench Electrum xmltv virt-manager" \
  -j 8

Computers / CPU cores / Max jobs to run
1:local / 8 / 8

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
ETA: 0s Left: 0 AVG: 0.88s  local:0/25/100%/0.9s  
Done.

real	0m26.416s
user	0m16.928s
sys     0m23.759s

**Comment by willysr** [comment]
It's now merged in afddeb5
