### ISSUE TITLE
sqg: incorrect glob expansion when *.info files are present in current directory

### ISSUE THREAD

**Issue by 414n** [sbopkg/sbopkg#36]
Greetings,

I just noticed today that sqg does not protect a `*` char from glob expansion while searching for *.info files inside the repository directory. This does not hinder normal functionality until the sqg command is run from a directory containing at least one *.info file: this way, only that file gets searched for in the repo and parsed.

Will soon send a PR with a fix.

**Comment by willysr** [comment]
Fixed in bef8ffc58bead55a0dd5f08274ea78453b87f990
