### ISSUE TITLE
self update with -u hangs

### ISSUE THREAD

**Issue by stuart-little** [sbopkg/sbopkg#40]
I am on Slackware 14.2, and have been running version 0.38.1 of sbopkg for quite some time with no problems to report. Today (Jan 17 2018) I started encountering the following issue: 

Running sbopkg -u hangs (returns no errors / warnings, etc.; it simply never returns to a command prompt, even after waiting a few minutes). 

htop reveals the task

wget -T 10 -q -O - https://sbopkg.org/currentversion

being run repeatedly. Running it directly in a terminal returns 0.38.1, as expected. Also, everything else seems to be in order (I did package updates with `sbopkg -rc` and then `-i` uneventfully before running `sbopkg -u`). 

I run checks for self-updates with -u regularly, and have never encountered the problem before.

**Comment by willysr** [comment]
I have it working here (although i'm using development version)

```
sbopkg -u

Checking https://www.sbopkg.org for an update...

Your version of sbopkg: 0.38.2

Latest version of sbopkg found on sbopkg.org: 0.38.1

Different versions reported. (D)ownload the remote package or (Q)uit?:
```

sbopkg is not updated that frequent. Most likely it will be updated once a new Slackware gets released, so there's no point of running sbopkg -u. Most likely you just need sbopkg -r to update your local repository.

**Comment by stuart-little** [comment]
Thanks for the quick reply!

Yeah, I figured the -u functionality would not come in handy too often: I never once upgraded sbopkg since I installed 14.2 maybe a year back, and I can always just get the newest version as a tgz. 

I was only curious about the sudden change in behavior and thought I'd ask (no change by the way, I still get no reaction from `sbopkg -u`). Should make for an interesting puzzle and I might learn something in the process. Any suggestions for how to track down what's going on, if only for instruction purposes?

**Comment by willysr** [comment]
sbopkg is behind cloudflare and you may end up reaching different cloudflare gateways around the world. It's just so happen that there's a small possibility that it would end up blocked by the original machine hosting sbopkg. I can tell because i experienced it myself last week before i can ask to remove the IP from blacklist.
