### ISSUE TITLE
checking for update doesn't work on 0.38.1

### ISSUE THREAD

**Issue by ArTourter** [sbopkg/sbopkg#43]
trying to check for sbopkg package update hangs in both ncurses mode and through the cli (sbopkg -u).

sbopkg becomes completely unresponsive and only a CTRL-C  gets out of it.

**Comment by willysr** [comment]
try to change -T 10 to -T 20 
https://github.com/sbopkg/sbopkg/blob/master/src/usr/sbin/sbopkg#L4108
https://github.com/sbopkg/sbopkg/blob/master/src/usr/sbin/sbopkg#L4110
https://github.com/sbopkg/sbopkg/blob/master/src/usr/sbin/sbopkg#L4112

Works fine here after i changed the timeout
```
sbopkg -u

Checking https://www.sbopkg.org for an update...

Your version of sbopkg: 0.38.2

Latest version of sbopkg found on sbopkg.org: 0.38.1

Different versions reported. (D)ownload the remote package or (Q)uit?:
```
