### ISSUE TITLE
Show version when searching using CLI

### ISSUE THREAD

**Issue by yars068** [sbopkg/sbopkg#45]
Hello. When searching packages on the [SBo](https://slackbuilds.org), we see the versions of packages. But does not, when searching using sbopkg. So, I tried to make it more comfortable. When searching with -g option, sbopkg will show version of packages. Thanks you! See [yars068:f070eb](https://github.com/yars068/sbopkg/commit/f070eb971500176a051c91356804b0fd0907f70d) for patch.

**Comment by willysr** [comment]
Thanks
it's now merged in master
