### ISSUE TITLE
sqg: .info files can lead to any command execution as root

### ISSUE THREAD

**Issue by swmarc** [sbopkg/sbopkg#46]
`ETA: 9s Left: 693 AVG: 0.01s  local:8/6450/100%/0.0s /var/lib/sbopkg/SBo/games/mrboom/mrboom_libretro.info: line 1: display_name: command not found
/var/lib/sbopkg/SBo/games/mrboom/mrboom_libretro.info: line 2: authors: command not found
/var/lib/sbopkg/SBo/games/mrboom/mrboom_libretro.info: line 3: supported_extensions: command not found
/var/lib/sbopkg/SBo/games/mrboom/mrboom_libretro.info: line 4: corename: command not found
/var/lib/sbopkg/SBo/games/mrboom/mrboom_libretro.info: line 5: categories: command not found
/var/lib/sbopkg/SBo/games/mrboom/mrboom_libretro.info: line 6: systemname: command not found
/var/lib/sbopkg/SBo/games/mrboom/mrboom_libretro.info: line 7: database: command not found
/var/lib/sbopkg/SBo/games/mrboom/mrboom_libretro.info: line 8: license: command not found
/var/lib/sbopkg/SBo/games/mrboom/mrboom_libretro.info: line 9: supported_extensions: command not found
/var/lib/sbopkg/SBo/games/mrboom/mrboom_libretro.info: line 10: permissions: command not found
/var/lib/sbopkg/SBo/games/mrboom/mrboom_libretro.info: line 11: display_version: command not found
/var/lib/sbopkg/SBo/games/mrboom/mrboom_libretro.info: line 12: supports_no_game: command not found`

Because `sqg` needs to run as root, this can have fatal effects if SBo admins overlook it in its review process.

**Comment by willysr** [comment]
This will be fixed in next public update as it should be downloaded as part of the DOWNLOAD, not as individual file. I have it fixed here: https://git.slackbuilds.org/slackbuilds/commit/?id=431ba7b9d

**Comment by willysr** [comment]
@swmarc can you check whether 46ba73b fixed this issue? please use latest master as base

Thanks

**Comment by swmarc** [comment]
@willysr Thanks for the quick fix. Works nicely.

`ETA: 7s Left: 690 AVG: 0.01s  local:8/6453/100%/0.0s \n
Found invalid .info file: /var/lib/sbopkg/SBo/games/mrboom/mrboom_libretro.info. Skipping.
ETA: 0s Left: 0 AVG: 0.01s  local:0/7143/100%/0.0s   
Done.`

**Comment by willysr** [comment]
Hm... i didn't expect "\n" there, it should be printed in new line instead of outputing it.

**Comment by swmarc** [comment]
Simply use `echo ""`. By default, it prints a newline without any options.

**Comment by swmarc** [comment]
Alternatively `echo -n -e "\nMy text\n"` for a oneliner and a newline at the beginning and end.
