### ISSUE TITLE
wrong link on sbopkg.org

### ISSUE THREAD

**Issue by pitchforks** [sbopkg/sbopkg#5]
On http://sbopkg.org/docs.php there's a line saying

    Click here for the sbopkg(8) man page.

It contains a wrong link that points to a raw HTML file that's not readable by humans. The link to the sbopkg.8 manpage should either point to a HTML version of the manpage that actually renders in the browser. Or just to the text version of the manpage, that's also human readable.

**Comment by willysr** [comment]
Fixed now. Thanks
