### ISSUE TITLE
Making sbopkg better

### ISSUE THREAD

**Issue by anselal** [sbopkg/sbopkg#53]
Hi there,

I thought that sbopkg is auto-installing the requirements of any given package.
Isn't that the case?

**Comment by anselal** [comment]
I just found out that I can use `sqg -a` to build queues for all packages or `sqg -p <package>` for a specific package.

Really Cool 😎 

If this is the only option then you can close this issue !!!

**Comment by willysr** [comment]
Yes, by default, it's not, but with the help of sqg, it would generate a queue file that can be used to auto-install the dependencies

**Comment by anselal** [comment]
really nice work !!!

thnx
