### ISSUE TITLE
sbopkg under cron produces stty ioctl errors

### ISSUE THREAD

**Issue by smallid** [sbopkg/sbopkg#55]
I am running a nightly sbopkg rsync and update check and the generated report includes numerous lines like this (on stderr): 
`stty: 'standard input': Inappropriate ioctl for device`

This behavior is displayed in the following minimal cron command:
`/usr/sbin/sbopkg -cq`

Actual cron command that I'm using:
`40 4 * * * /usr/sbin/sbopkg -rucq`

Can sbopkg be enhanced to be more cron friendly? Am I missing some configuration option which would resolve the issue without throwing away all stderr output?

**Additional Notes:**
I think that the issue may be related to internal redirection to /dev/null. For example, in `progressbar()` if I remove the else block, which contains `cat > /dev/null`, then the number of error lines is greatly reduced.

```
progressbar() {
 <snip>
    elif [[ ! $QUIET ]]; then
        progressbar_cli "$MSGTITLE" "$MSGTEXT"
    # else
    #    cat > /dev/null
    fi
}
```

**Comment by willysr** [comment]
can you try to use sbopkg -r instead of rucq?

**Comment by smallid** [comment]
Here is the output of `sbopkg -r`:

```
Syncing with the remote repository into /var/lib/sbopkg/SBo/14.2.

Rsync with the SBo repository for Slackware 14.2 complete.

Importing SBo repository for Slackware 14.2 GPG Key...
Import done.

***SYNC COMPLETE***
[?25h[?0c
```

**Comment by willysr** [comment]
What's with these "[?25h[?0c" character? i don't have that output here

anyway, you should not use sbopkg -r in cron as the updates were usually pushed weekly and it is always announced in the mailing list. So i suggest to join the list and run sbopkg -r once a new public update is pushed.

**Comment by smallid** [comment]
If sbopkg supports command-line mode operations then I believe it should be possible to run under cron. 

I'm also confused why you asked me to run `sbopkg -r` under cron and now you are saying that it shouldn't be run under cron. What information were you looking for? Are you trying to reproduce the issue by running the script via a terminal instead of via a cron job?

**Comment by willysr** [comment]
i normally use sbopkg on a terminal, not in cron :)

yes, i wanted to see the results when you run the command in command line and also in cron since it should be the same, but nevertheless you get the garbled output at the end of the command. That confused me....

**Comment by smallid** [comment]
The garbled output only shows up when I run in cron, but not when I run in a terminal. I think it's likely they are an artifact of non-printable command codes (things like moving the cursor and changing text color or other terminal commands). Cron doesn't deal well with those because it is not a terminal.

**Comment by willysr** [comment]
what's your locale? is it en_US.UTF-8 ?

**Comment by smallid** [comment]
It looks like in the terminal it is en_US.UTF-8 but under cron it is 'POSIX'

**Comment by smallid** [comment]
I looked some more at the 'stty' part of the error message and that lead me to what I think is the cause: 

`read_nonblock()` - uses stty
`progressbar_interrupted()` - calls `read_nonblock()`
`check_for_updates()` - calls `progressbar_interrupted()` every package

When running under cron, there is no interactive terminal, so the stty call causes an error message to be generated.

The extra characters are caused by ncurses related functionality: I see that HAS_NCURSES is set if the tput executable exists, but there is no check for whether ncurses can be run in the current environment.

`[[ -x /usr/bin/tput ]] && HAS_NCURSES=1`
