### ISSUE TITLE
-R flag only works before -i flag

### ISSUE THREAD

**Issue by Tonus1** [sbopkg/sbopkg#59]
Hi,

On current (2019-12-31), with latest sbopkg (0.38.1) :
`sbopkg -iR _package_` or `sbopkg -i -R _package_`

gives

`Error: unknown token "_package_"`

while

`sbopkg -Ri _package_` works as expected.

Regards

**Comment by willysr** [comment]
Hi @Tonus1 

this is because -i needs to be followed by a package name
please check man sbopkg for usage.

This is not a bug

**Comment by Tonus1** [comment]
I have misread the help, sorry for the noise.
