### ISSUE TITLE
always need root

### ISSUE THREAD

**Issue by goarilla** [sbopkg/sbopkg#6]
It would be nice if normal users could search sbopkg -g slackbuild.
I have a "fork" now with a patch ? This is my first gitstuff so I'm unsure if this is the right way.

**Comment by willysr** [comment]
sbopkg is designed to be run by root and i still prefer to keep it that way.

**Comment by goarilla** [comment]
So what happens now ? We wait until other people can convince you or me :D 
Should I still do this "pull request" ?

**Comment by willysr** [comment]
sure, please submit git pull
make sure it's a clean changes without changing any other part of the code that you shouldn't change like in the previous patch

**Comment by goarilla** [comment]
OK but then I'll have to start a new issue (pidfile) and do some more work.

**Comment by willysr** [comment]
PIDFILE issue is now fixed with f2978fae7cca101a5a2c6b101ef8fbc329b2edcd
