### ISSUE TITLE
sbopkg not running in batch mode when there's ambiguity between package and queue name

### ISSUE THREAD

**Issue by somospocos** [sbopkg/sbopkg#60]
Affected version: 0.38.1

How to reproduce:

- generate a queue for APPNAME
- try running sbopkg in batch mode `sbopkg -i APPNAME`
- it interactively asks the user to pick the queue or the package
- adding -B doesn't help

User needs a way to specify that sbopkg must prefer a queue or a package in this ambiguous situation through command line arguments, thus making it possible for sbopkg to manage queues properly in full batch mode.

Ideally, this feature must be supported as well in the sbopkg version that works with Slackware 14.2, because 15.0 doesn't have a fixed release date and the release of 15.0 won't completely obsolete 14.2 anyway.

Some discussion about it here: https://www.linuxquestions.org/questions/slackware-14/correct-universal-way-of-building-installing-sbo-package-in-batch-mode-4175672375/

**Comment by willysr** [comment]
-B is already working as designed.
See here https://www.linuxquestions.org/questions/slackware-14/correct-universal-way-of-building-installing-sbo-package-in-batch-mode-4175672375/page2.html#post6107296

**Comment by somospocos** [comment]
Sorry, but this isn't a bug report about -B not working as designed.

This is a bug report about sbopkg not running in batch mode when dealing with queues.

**Comment by willysr** [comment]
isn't that what -B is used for?
if you run sbopkg -B -i APPNAME, you need to pick QUEUE and it will run in batch mode

**Comment by somospocos** [comment]
Answered in LQ thread, to avoid splitting up the discussion.
