### ISSUE TITLE
Cannot call dir_init non-interactively in 0.38.1

### ISSUE THREAD

**Issue by perrin4869** [sbopkg/sbopkg#63]
I'm trying to setup an automated `sbopkg` environment, but am stuck at the initialization phase - whenever I run `sbopkg` for the first time, it prompts me to press `(C)` or `(A)` for creating the necessary directories.

https://github.com/sbopkg/sbopkg/blob/ae4f59c867699389ad35775e3a04f4f6e572b5ac/src/usr/sbin/sbopkg#L269

Right now the the only way to proceed is to manually create the required directories.
It would be very useful if the function above could be called from the command-line non-interatively.

**Comment by willysr** [comment]
it's already fixed by f93839fb3200de5463b0570976d3f284d64511fd
