### ISSUE TITLE
Modified Slackbuild in tui not archived in /usr/doc

### ISSUE THREAD

**Issue by jecxjo** [sbopkg/sbopkg#65]
When a SlackBuild file is updated in the terminal UI, for example to support a later version than in the repo, the version of the file that is archived is the original. The default for SlackBuild files look to archived `$CWD/$PRGNAM.SlackBuild`. This makes the version and configuration of the installed package not match the version found in `/usr/doc/<pkgname>-<pkgversion>`

**Comment by willysr** [comment]
Is this on 0.38.1 or latest master?

Did you check this? 371284cd8972641ece61957a76fe5629651e6c6a

**Comment by jecxjo** [comment]
Will check the the build, issue was seen in 0.38.1

**Comment by willysr** [comment]
one more thing, is this on -stable or in -current?
if you are in -current, can you test using this package? https://sbopkg.org/test/sbopkg-0.38.2-noarch-1_wsr.tgz
it's the latest package from master branch i generated like last week
