### ISSUE TITLE
Using SBo-git repo takes to much time and space

### ISSUE THREAD

**Issue by djunzu** [sbopkg/sbopkg#67]
Hi!

I am trying to use sbopkg with the unofficially slackbuilds repo for Slacwakre-current provided by Ponce, as stated in [here](https://github.com/Ponce/slackbuilds/wiki/configuring-the-current-repository-with-sbopkg).

When sbopkg clones SBo-git repository, it downloads more than 300 MB! Ignoring it's too much space wasted, every time I need to update the repo with `rm -fR /var/lib/sbopkg/SBo-git` and `sbopkg -r` it takes a little too much time.

Instead of cloning all repository, should it be possible to clone just the last commit with git parameter `--depth 1`?

I am not familiar with sbopkg code and I don't know if it would impact the others repos. But I think it is worth of consideration.

Thanks.

**Comment by willysr** [comment]
That's normal as the SBo-git from ponce is **rebased** against latest SBo master every public update in SBo.

it has been mentioned in the **READ BELOW!** section

**Comment by djunzu** [comment]
I don't know if I make myself clear...

I understand SBo-git from ponce is rebased frequently. That is not the point.

The point is downloading 300 MB of useless data. 
Even if there was no rebase in SBo-git and it was downloaded just once, it is more than 300 MB of disk space wasted for nothing.

The **only information needed from the repo is the last commit**. There is no need for nothing more. So, why download everything?
And this can be simply accomplished with git parameter `--depth 1`.

And I don't know if sbopkg uses git for stable Slackware releases also. If that is the case, the same principle applies.

And I don't know the growth rate of ponce's repo size. But at some point the repo will be 1GB in size. Does it makes sense to download 1GB of data, even a single time, just to have "a bunch of text files"? It makes no sense at all!

A git repo is by definition is a collection from all changes made in a set of files. sbopkg does not need the history of changes. It needs just the last state. The current state. And that is: the last commit.
So, again, why to download more than 300MB of "trash"? (Trash from the point of view of sbopkg.)

**Comment by willysr** [comment]
Ponce's repository is basically the same as in master branch of SBo, but his "current" branch is a collection of fixes that only applies for -current and he merged it from all individual branches that he had for each package. That's why it's rebased every week after public update has been pushed.

As to why it needs to be re-downloaded again is because current branch have a chance of having so many conflict after a new public update is pushed and rebased needed to be done, so it's easier to just remove the repository and restart the whole process. The 300MB of data is what the history of SBo git commits since the start of the repository.

**Comment by djunzu** [comment]
I definitely did not make my self clear!
You are just stating what I already know... And that is not the point.

> The 300MB of data is what the history of SBo git commits since the start of the repository.

That is exactly the point! sbopkg does not need all commits history since the start of the repository. It needs just the last commit!

But never mind...

**Comment by willysr** [comment]
You can't just grab the last commit when using current branch of ponce's repository as the history is rewritten due to changes in master branch of SBo.

**Comment by djunzu** [comment]
Yes you can.

`git clone --single-branch --branch current --depth 1 https://github.com/Ponce/slackbuilds.git`

It will work every single time.

**Comment by Ponce** [comment]
hi @djunzu !

I'm not the author of the sbopkg bit that manages handling of git repos but it's actually this bit of the script
```
checkout_git_branch() {
    # This function makes sure that in $REPO_DIR there's the currently
    # selected branch.
    # This is the implementation for git repositories, which is relatively
    # complex because we have to manage local changes.

    local CURRENT_BRANCH NEW_BRANCH NEW_STASH
    local COMMAND_OUTPUT=$SBOPKGTMP/sbopkg_git_checkout_output

    rm -f $COMMAND_OUTPUT

    # Make sure the repository is there
    [[ -d $REPO_DIR/.git ]] || return 0

    # No need to checkout if the right branch is already there
    NEW_BRANCH=$(cut -d@ -f2 <<< $REPO_LINK)
    cd $REPO_DIR
    CURRENT_BRANCH=$(git branch | grep '^*')
    CURRENT_BRANCH=${CURRENT_BRANCH//'* '}
    [[ $CURRENT_BRANCH = $NEW_BRANCH ]] && return 0

    # So we need to checkout the branch. First off, let's clean the tree
    echo "*/*/*.sbopkg" > .gitignore
    git clean -d -f > $COMMAND_OUTPUT
    git reset --hard HEAD >> $COMMAND_OUTPUT

    # Let's save the current user customizations to a stash
    git add . >> $COMMAND_OUTPUT
    git stash save sbopkg-auto-$CURRENT_BRANCH >> $COMMAND_OUTPUT

    # Checkout the user-requested branch
    git checkout $NEW_BRANCH >> $COMMAND_OUTPUT 2>&1

    # Pop the stash of this branch, if any
    NEW_STASH=$(git stash list | grep ": sbopkg-auto-$NEW_BRANCH\$" |
        cut -d: -f1)
    if [[ -n $NEW_STASH ]]; then
        git stash pop $NEW_STASH >> $COMMAND_OUTPUT
        # Make sure no changes are staged
        git reset HEAD >> $COMMAND_OUTPUT
    fi

    # Create a changelog
    # (it makes no sense to have one tracked in a git repo)
    if [[ ! -f ChangeLog.txt ]]; then
        git log --pretty=format:"%cd%n%s%n%b" > ChangeLog.txt
    fi
}
```
I have not checked but in your opinion will still work (will it handle local changes) if we clone the repository with the command you propose?

**Comment by Ponce** [comment]
BTW, to clarify, @willysr , looking better at this the change that @djunzu proposes to the present code is this
```
--- ./src/usr/sbin/sbopkg.orig	2020-10-06 18:51:21.542592000 +0200
+++ ./src/usr/sbin/sbopkg	2020-10-06 18:49:37.215592000 +0200
@@ -2446,6 +2446,7 @@
     if [[ $REMOTE != $LOCAL ]]; then
         cd ..
         rm -fR $REPO_DIR
+        git clone --single-branch --branch current --depth 1 $URL $REPO_DIR
     fi
 }
 
```
and this actually shouldn't involve the general code that handles git repositories as it's already handled as a special case.

**Comment by willysr** [comment]
ok, thanks, will push this.
Thanks @djunzu for the suggestion

**Comment by djunzu** [comment]
@Ponce 
I don't know how sbopkg handles git repositories. Therefore, I don't know how it would affect others repositories.

**Comment by djunzu** [comment]
@Ponce, @willysr 
I would like to have made the PR myself. But I am not fluent in bash script... And I have some difficulty with sbopkg internal code. 

Out of curiosity...

```bash
$ time git clone --single-branch --branch current --depth 1 https://github.com/Ponce/slackbuilds.git .
Cloning into '.'...
remote: Enumerating objects: 45897, done.
remote: Counting objects: 100% (45897/45897), done.
remote: Compressing objects: 100% (41863/41863), done.
remote: Total 45897 (delta 13399), reused 20841 (delta 3746), pack-reused 0
Receiving objects: 100% (45897/45897), 23.29 MiB | 1.24 MiB/s, done.
Resolving deltas: 100% (13399/13399), done.
Updating files: 100% (39679/39679), done.

real	0m24.183s
user	0m3.897s
sys	0m1.557s

$ du -hs
212M	.

$  time git clone https://github.com/Ponce/slackbuilds.git .
Cloning into '.'...
remote: Enumerating objects: 147, done.
remote: Counting objects: 100% (147/147), done.
remote: Compressing objects: 100% (147/147), done.
remote: Total 477979 (delta 119), reused 15 (delta 0), pack-reused 477832
Receiving objects: 100% (477979/477979), 131.64 MiB | 1.24 MiB/s, done.
Resolving deltas: 100% (331736/331736), done.
Updating files: 100% (39679/39679), done.

real	1m55.711s
user	0m25.912s
sys	0m5.625s

$ du -hs
332M	.
```

It's 5 times faster to clone the repo with `--depth 1`. And one third less disk usage.

Thanks!

**Comment by willysr** [comment]
No problem, your suggestions really helped and thanks for further testing
