### ISSUE TITLE
MEGASync not compiling (log included)

### ISSUE THREAD

**Issue by int-var86** [sbopkg/sbopkg#69]
Hello, MEGASync is not compiling, log attached (and a picture included)
![sbopkg-megasync](https://user-images.githubusercontent.com/84349991/120127045-97246f00-c194-11eb-9937-5fb37570da0c.png)
[MEGASync_not_compiling.tar.gz](https://github.com/sbopkg/sbopkg/files/6567250/MEGASync_not_compiling.tar.gz)

**Comment by int-var86** [comment]
On Slackware 14.2 (without any updates)

**Comment by willysr** [comment]
have you build and install all dependencies for MEGASync?

**Comment by int-var86** [comment]
> have you build and install all dependencies for MEGASync?

So this is not a bug? (I don't have Slackware 14.2 anymore to test)

**Comment by willysr** [comment]
No, you need to install dependencies first, either manually or use sqg to generate the queue file first for MEGAsync
