### ISSUE TITLE
integrate sbotools + sbopkg

### ISSUE THREAD

**Issue by drbeco** [sbopkg/sbopkg#72]
I'm currently trying to use sbotools and sbopkg pointing to the same repository.

Currently with the directory to repo substituted to a symlink to sbopkg repository (actually rsync mirror).

The command used to create the link was  a simple:

```
[/usr/sbo/]# ln -s /var/lib/sbopkg/SBo/14.2 repo 
```

For now it is working fine, but I'm concerned with this file diff:

```
diff -q repo.orig/ /var/lib/sbopkg/SBo/14.2/
> Files repo.orig/SLACKBUILDS.TXT and /var/lib/sbopkg/SBo/14.2/SLACKBUILDS.TXT differ
```
I guess SLACKBUILDS.TXT from sbopkg includes MD5SUM and other info, while sbotools only needs name/location.

If we could integrate both better, that would be great.

----

One step to a better integration would be considering instead of rsync mirror, a git repository. 

That way both tools could do a "repo upgrade" that would be equivalent.

Thanks

**Comment by willysr** [comment]
these two projects are different in design, so i'm not really sure about this idea

**Comment by drbeco** [comment]
Thanks Sir Willy, for your reply.

I understand that. But as long as both keep the original repository intact, and use them without modifiying them, they would be able to get files from the same repo and save us some HD space.

**Comment by willysr** [comment]
sbopkg by default don't change anything from the original repo unless the user make a local edit or use different repository / branches, so the SLACKBUILDS.TXT should not be different

**Comment by drbeco** [comment]
That is great. I wrote a similar issue on the sbotools git , and I think we can close this one.
