### ISSUE TITLE
queue no longer works

### ISSUE THREAD

**Issue by dchmelik** [sbopkg/sbopkg#79]
On Slackware64 15.1-current w/sbopkg 0.38.2 and even upgraded to 20220318-8bf4e6a, the queue menu no longer works.
        I synchronize repository, select check for updates, get over a page of results, go to queue, select any command (like process, remove, sort, view, etc.) and nothing happens: simply immediately returns to queue menu in split-second so the only thing appearing to happen is terminal flashes (as redrawn.)

**Comment by willysr** [comment]
![image](https://user-images.githubusercontent.com/240100/161260434-e31e1747-8d33-4496-869a-227f4b7ac091.png)
I get the queue updates here

**Comment by dchmelik** [comment]
Don't you want me to check a log (error log, obviously not build log) or must I just erase all my configuration, uninstall, reinstall, slowly remake configuration starting from default/nothing?

**Comment by willysr** [comment]
i'm more curious about how you setup sbopkg in your machine

**Comment by dchmelik** [comment]
I had updated the following.
```
#/etc/sbopkg/sbopkg.conf
REPO_BRANCH=${REPO_BRANCH:-current}
REPO_NAME=${REPO_NAME:-SBo-git}
```

**Comment by willysr** [comment]
try this
```
REPO_BRANCH=${REPO_BRANCH:-master}
REPO_NAME=${REPO_NAME:-SBo}
```

**Comment by dchmelik** [comment]
The same thing happened.  Actually some commands work: I can sort, maybe load, and save, but not view, remove, process (didn't try rename or delete because don't have any saved, and didn't try add all because not Slackware 15.1 stable yet.)

**Comment by willysr** [comment]
do you have any other changes in locale or environment variables?
can you try to load sbopkg in a clean environment like VM?

**Comment by dchmelik** [comment]
I have default locale and the following environment variables.

```
export ANT_HOME=/usr/lib64/ant
export ARCH=x86_64
export EDITOR=nano
export HOSTNAME='`cat /etc/HOSTNAME`'
export JAVA_HOME=/usr/lib64/jdk11-11.0.14
export JAVAC=/usr/lib64/jdk11-11.0.14/bin/javac
export JAVAH=/usr/lib64/jdk11-11.0.14/bin/javah
export JAVA_BASE=/usr/lib64/jdk11-11.0.14
export JAVADOC=/usr/lib64/jdk11-11.0.14/bin/javadoc
export CLASSPATH=/usr/lib64/jdk11-11.0.14/lib
export LESSOPEN="|lesspipe.sh %s"
export LESS="-M -R"
export MAKEFLAGS="-j31"
export MINICOM="-c on"
export MANPATH="/usr/local/man:/usr/man"
export PKGTYPE=txz
PATH=/usr/local/sbin:/usr/sbin:/sbin:/etc:/etc/rc.d:/etc/init.d:/var/log/setup:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/local/games:{JAVA_HOME}:/usr/lib64/ant/bin:/opt/notepadqq/bin:/usr/share/ant/bin:/opt/ex-vi/bin:/usr/lib64/go1.17.7/go/bin:/opt/idea/bin:/usr/lib64/libexec/kf5:/opt/plan9/bin:/usr/lib64/qt5/bin:/opt/scilab/bin:/usr/lib64/zulu-openjdk7/bin:/usr/lib64/zulu-openjdk7/jre/bin:/usr/lib64/zulu-openjdk8/bin:/usr/lib64/zulu-openjdk8/jre/bin:.
TERM=linux
PS1='\u@\l${STY#[0-9]*.}.\h:\w\$ '
PS2='> '
```
There's no point using virtual environment because I'm not installing Slackware-current packages anywhere else.  If my installation is supposedly'dirty' I want to find out how and fix.

**Comment by willysr** [comment]
i also run slackware-current at home and it works fine here
can you try to add set -e on top of sbopkg script and see where it throws error at?

**Comment by dchmelik** [comment]
I made a line 'set -e' near top of /usr/sbin/sbopkg if that's what you mean, but currently don't have updates to do.  Same started happening on Slackware 15 up-to-date stable x86(-64) and arm (haven't tested x86-32.)

**Comment by Geremia** [comment]
I get this issue, too. I never had it before.

@willysr 
`set -e` makes sbopkg quit when I choose update.

`bash -x /usr/sbin/sbopkg` outputs this when I choose "View&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;View the current queue", after running update:
```+ CHOICE=255
+ [[ 255 -eq 2 ]]
+ selection_state preserve /tmp/sbopkg.VJoY4a/sbopkg-tmp-queue /tmp/sbopkg.VJoY4a/sbopkg-ans-queue
+ local ACTION=preserve
+ local MENU_FILE=/tmp/sbopkg.VJoY4a/sbopkg-tmp-queue
+ local SELECTION_FILE=/tmp/sbopkg.VJoY4a/sbopkg-ans-queue
+ local LINE
+ sed -i 's/ON$/OFF/' /tmp/sbopkg.VJoY4a/sbopkg-tmp-queue
+ read LINE
+ sed -i '/^"*"* /s/OFF$/ON/' /tmp/sbopkg.VJoY4a/sbopkg-tmp-queue
+ read LINE
+ sed -i '/^"*3 arguments attendus, 2 trouvés en trop."* /s/OFF$/ON/' /tmp/sbopkg.VJoY4a/sbopkg-tmp-queue
+ read LINE
+ sed -i '/^"*Use --help to list options."* /s/OFF$/ON/' /tmp/sbopkg.VJoY4a/sbopkg-tmp-queue
+ read LINE
+ sed -i '/^"*"* /s/OFF$/ON/' /tmp/sbopkg.VJoY4a/sbopkg-tmp-queue
+ read LINE
+ sed -i '/^"*"* /s/OFF$/ON/' /tmp/sbopkg.VJoY4a/sbopkg-tmp-queue
+ read LINE
+ [[ preserve == reverse ]]
+ case $CHOICE in
+ mv /tmp/sbopkg.VJoY4a/sbopkg-original-queue /tmp/sbopkg.VJoY4a/sbopkg-tmp-queue
+ rm -f /tmp/sbopkg.VJoY4a/sbopkg-ans-queue
```

**Comment by willysr** [comment]
here's what i have now (i just ran sbopkg in GUI mode and check updates and view the queue)
![image](https://user-images.githubusercontent.com/240100/167012993-890581ea-3d0a-4836-b7f0-0f342e3966e7.png)

**Comment by Geremia** [comment]
@willysr  If I say no to "would you like to add flagged updates to the queue" after checking for updates, nothing is added (I guess all the updates were flagged in my case?).

**Comment by willysr** [comment]
we don't have that option for now (sbopkg -c -> queue)

but if you say no to the question about adding flagged potential updates, then it's normal for queue to be empty since you said no.

can you make a short video on how you do things so i can reproduce it here?

**Comment by Geremia** [comment]
@willysr Here's a screencast: 

https://user-images.githubusercontent.com/4298614/167187976-be1237f2-d2c6-44e9-ada4-bf4303b2a8a8.mp4

<sup>(I cut out 1 min. of the updating time, to keep the video ≤10MB).</sup>

**Comment by Geremia** [comment]
A workaround: Run update in the GUI, save the queue as "updates", and process it with `sbopkg -i updates -e continue`.

**Comment by willysr** [comment]
@Geremia after i looked over your video, it seems you are using an older version of sbopkg (probably pre-released version) since it has 2021 as the copyright (see 0:04), while the latest sbopkg has 2022 in the copyright year. Can you check using the latest version of sbopkg downloaded from official website? thanks

**Comment by dchmelik** [comment]
I've had all above and now more problems with post-release 0.38.2 and subsequent/y upgraded/configured git version(s) which now also instead of doing any/all command-line arguments/flags/switches just start sbopkg GUI.

**Comment by willysr** [comment]
so this issue can also be closed?

**Comment by dchmelik** [comment]
I still have the problem on 0.38.2 & 8bf4e6a; didn't change anything when tried workaround and using much smaller queue than huge ones that used to work.

**Comment by willysr** [comment]
so what command did you use now?

**Comment by dchmelik** [comment]
> so what command did you use now?

`root@cosmos:~# sbopkg`

**Comment by willysr** [comment]
i mean, to create the queue

**Comment by dchmelik** [comment]
I created the queue in the GUI same way as shown in the video; this isn't solved!

**Comment by willysr** [comment]
it's working fine in many other machines, so unless you try it in a clean environment, i am not convinced with how you test it
