### ISSUE TITLE
[0.38.2, 8bf4e6a] command-line broken

### ISSUE THREAD

**Issue by dchmelik** [sbopkg/sbopkg#81]
Sbopkg command-line arguments/flags/switches just seem to open GUI.

'sbopkg -r' may not update (though there may not have been one) and opens GUI (but shouldn't, should it?).

'sbopkg -S -i /var/lib/sbopkg/queues/nix.sqf' doesn't build that existent queue and opens GUI (but shouldn't, should it?).

Some/all others may but forgot which I tested (maybe not all).

I forgot of 0.38.2 does (might on Slackware-current but maybe not stable) but don't feel like downgrading, though could test my Slackware-stable servers & laptops later.

**Comment by willysr** [comment]
if sbopkg -r is not working, you might have a broken sbopkg installation or wrong configuration

**Comment by dchmelik** [comment]
I tested multiple 0.38.2, 8bf4e6a installs & reinstalls with default configuration.

**Comment by willysr** [comment]
probably start by posting your sbopkg.conf

**Comment by willysr** [comment]
NICE is to handle priority of a process
you can check `man nice` for that

**Comment by willysr** [comment]
```
sbopkg -S -i /var/lib/sbopkg/queues/nix.sqf
/usr/sbin/sbopkg: line 2031: /var/lib/sbopkg/queues//var/lib/sbopkg/queues/nix.sqf: No such file or directory
No valid queuefile or package name given.  Exiting.
```
you should be running sbopkg -S -i nix

**Comment by dchmelik** [comment]
Okay. As you see the problem was something else (I'll explain later).
```
# $Id$
#
# Please read the sbopkg.conf(5) man page for information about this
# configuration file, including an explanation of how to set these
# variables.

# The following variables are used by sbopkg and by the SlackBuild
# scripts themselves.  They must be exported for this reason.
export TMP=${TMP:-/tmp/SBo}
export OUTPUT=${OUTPUT:-/tmp}

# The following are variables used by sbopkg.  Any of these variables
# could be exported, if desired.

# Path variables
LOGFILE=${LOGFILE:-/var/log/sbopkg/sbopkg-build-log}
QUEUEDIR=${QUEUEDIR:-/var/lib/sbopkg/queues}
REPO_ROOT=${REPO_ROOT:-/var/lib/sbopkg}
SRCDIR=${SRCDIR:-/var/cache/sbopkg}
BLACKLISTFILE=${BLACKLISTFILE:-/etc/sbopkg/blacklist}
# sbopkg's temporary directory (where its internal temporary files are
# kept and where packages are made prior to being moved to OUTPUT)
# defaults to /tmp/sbopkg.XXXXXX where 'XXXXXX' is a random string. If
# /tmp is not a suitable containing directory, pass in an alternate
# TMPDIR or modify the following variable. This is actually a mktemp(1)
# variable.
export TMPDIR=${TMPDIR:-/tmp}

# Other variables:
CLEANUP=${CLEANUP:-NO}
DEBUG_UPDATES=${DEBUG_UPDATES:-0}
KEEPLOG=${KEEPLOG:-YES}
MKDIR_PROMPT=${MKDIR_PROMPT:-NO}
NICE=${NICE:-10}
REPO_BRANCH=${REPO_BRANCH:-15.0}
REPO_NAME=${REPO_NAME:-SBo}
#REPO_BRANCH=${REPO_BRANCH:-master}
#REPO_NAME=${REPO_NAME:-SBo}
#REPO_BRANCH=${REPO_BRANCH:-current}
#REPO_NAME=${REPO_NAME:-SBo-git}

# The following variable determines if multiple instances of sbopkg can
# be run simultaneously. It is *strongly* recommended that this value be
# set to NO. Do not set it to YES without first reading the
# sbopkg.conf(5) man page.
ALLOW_MULTI=${ALLOW_MULTI:-NO}

# The following variables are required and can be tweaked if desired,
# although this is not recommended.  Note:  rsync already uses
# --archive, --delete, --no-owner, and --exclude in the main sbopkg
# script so there is no need to add those flags here.
DIFF=${DIFF:-diff}
DIFFOPTS=${DIFFOPTS:--u}
RSYNCFLAGS="${RSYNCFLAGS:---verbose --timeout=30}"
WGETFLAGS="${WGETFLAGS:--c --progress=bar:force --timeout=30 --tries=5}"

# SRC_REPO defaults to "http://slackware.uk/sbosrcarch". To use
# a different repository, uncomment and edit this variable. The value
# must be the URL of the directory containing the by-name and by-md5
# sub directories, and should NOT have a trailing slash.
# SRC_REPO="http://slackware.uk/sbosrcarch"

```

**Comment by willysr** [comment]
MKDIR_PROMPT=${MKDIR_PROMPT:-NO}
this should be
MKDIR_PROMPT=${MKDIR_PROMPT:-YES}

it has been changed for 0.38.2

**Comment by dchmelik** [comment]
A minute ago I uninstalled sbopkg (including sbopkg.conf.new) and redownloaded 0.38.2 from sbopkg.org, and the sbopkg.conf.new I got has 'MKDIR_PROMPT=${MKDIR_PROMPT:-NO}'; same when upgraded to 8bf4e6a.  I don't even know what that line does but certainly didn't change it.

**Comment by willysr** [comment]
sorry my bad, it should be NO. it's already correct, since it's now creating directory by default

**Comment by dchmelik** [comment]
Apparently all did so problem (solved) was because I never used sgopkg command-line until recent years, and aliased to 'sbopkg && reset': often afterwards had blank terminal (no cursor nor writing appearing)... maybe I'd have to put some variables in for that to work with command-line but don't know how many.
