### ISSUE TITLE
sqg -a

### ISSUE THREAD

**Issue by robindesvils** [sbopkg/sbopkg#82]
When I use
sqg -a

I  get:
# sqg -a
Setting system wide configuration in /etc/sbopkg/sbopkg.conf
Processing all SlackBuilds in the SBo/15.0 repository.../usr/libexec/sbopkg/sqg/functions: line 238: parallel: command not found
Done.

Any comment appreciated

**Comment by willysr** [comment]
parallel is included in Slackware 15.0
you probably didn't use full installation or you missed that package during upgrade process
