### ISSUE TITLE
sqg -o missing dependency

### ISSUE THREAD

**Issue by bassmadrigal** [sbopkg/sbopkg#83]
I was working on upgrading my htpc to 15.0 over last weekend.

The system pretty much only runs kodi on top of a full Slackware install. I tend to keep my kodi fully featured, so I include all optional dependencies. To get my build queue, I ran the following:

`sqg -p "avahi cwiid dav1d libcec libmicrohttpd libnfs lirc shairplay kodi" -o kodi-full`

However, the resulting queue ended up missing several packages, including cwiid, dav1d, libmicrohttpd, libnfs, and lirc, even though they were included in the command:

```
libdaemon
avahi
platform
libcec
libdaemon
avahi
shairplay
pycryptodomex
gtest
tinyxml
spdlog
rapidjson
fmt
flatbuffers
libass
zulu-openjdk11
kodi
```

This does not occur if I add those dependencies directly to the REQUIRES line in the kodi.info and then run sqg against kodi. I've tested this on two different machines with the latest stable release of sbopkg on fully up-to-date Slackware 15.0 full installs. sbopkg is set to the 15.0 repo and sqg has been tested with OPT_JOBS set to both 1 and 4.

It also duplicated avahi and libdaemon.

I currently don't have time to properly debug this and provide a potential fix, but for the missing packages, it seems to be packages that don't have their own dependencies. Normally, it makes sense to not include them unless  OPT_ALL is set, but if one is creating a custom queue file, it should include all packages, regardless of whether OPT_ALL is set.

I'm not sure the cause for the duplicate packages and why they weren't consolidated to a single entry.

My IRL job is a bit crazy right now with me working 60 hour work weeks, but I can likely look into this more in depth around mid-November, unless someone else gets to it first.

**Comment by willysr** [comment]
This feature was introduced here: fe264c391e9254139ee194d1407ca2f52a319e73

**Comment by willysr** [comment]
i think because sqg is designed to create queues to solve dependencies, so those who don't have dependencies will not be created and listed.

**Comment by willysr** [comment]
that's the reason why i remove SKIP_EMPTY option in ba15355444a923a31a9594f5b861ae52e6452574

**Comment by willysr** [comment]
I pushed a fix for the duplicate lines in 720a874.
Can you confirm that commit fixed the duplicate lines?

**Comment by bassmadrigal** [comment]
> that's the reason why i remove SKIP_EMPTY option in [ba15355](https://github.com/sbopkg/sbopkg/commit/ba15355444a923a31a9594f5b861ae52e6452574)

In my mind, it seems when building a custom queue, you'd expect all programs listed in the command to be included in the queue file, regardless of whether or not those programs have dependencies. The ability to create a custom queue file with sqg shouldn't hinge on whether or not those programs have dependencies. In my above command, I was wanting to create a single queue file that would build everything I needed for kodi, including all optional dependencies. Leaving out the packages that didn't have dependencies worked contrary to what I imagine someone would expect if they're having sqg generate a custom queue.

I understand not having SKIP_EMPTY available for sqg in normal operations, but it seems like it would be extremely beneficial to include the functionality when building a custom queue.

> I pushed a fix for the duplicate lines in [720a874](https://github.com/sbopkg/sbopkg/commit/720a874d6002ecebc3a8159fd5f0d29462ae95e7). Can you confirm that commit fixed the duplicate lines?

I can confirm this fixes it. Thanks!

**Comment by willysr** [comment]
that would be reverting changes on SKIP_EMPTY i guess

**Comment by bassmadrigal** [comment]
Maybe the functionality could just be used when a custom queue is generated and not introduce it back as an option for single packages?

**Comment by willysr** [comment]
let me see if i can spend some time on this, i think i have an idea on that

**Comment by willysr** [comment]
@bassmadrigal can you confirm that 7cbb2f3 fix this issue for you?

**Comment by willysr** [comment]
@bassmadrigal can you confirm on latest commit? Does it fixed your issue?
