### ISSUE TITLE
sbopkg incorrectly returns '0' when build fails

### ISSUE THREAD

**Issue by andy5995** [sbopkg/sbopkg#85]
To reproduce:

`sbopkg -B -b PDCurses -e stop`

`0` is returned. (Build fails because it can't find 'Intrinsic.h').

**Comment by willysr** [comment]
i think that is the intended behaviour, since the process ended by writing the result to log (which is a success), although the build failed

**Comment by andy5995** [comment]
Ok. My thinking was that it would be better if non-zero is returned,  so when sbopkg is run from a script or a CI, they would also exit with non-zero when a non-interactive option (e.g. -B) was given.

If you're sure you want to keep the behavior as-is, feel free to close the ticket. Thanks for the response @willysr
