### ISSUE TITLE
using gslapt to download packages but without installation

### ISSUE THREAD

**Issue by robindesvils** [sbopkg/sbopkg#88]
Hello,

Would it be possible to add an option to package fetching of downloading a package including dependencies without installing them on the system. Something similar to the pacman -Sw <name of package>? This would be very useful for our distribution named Porteus.

Thanks.

**Comment by willysr** [comment]
I'm sorry, but sbopkg is designed to build packages using SlackBuild scripts provided by SBo. We don't work with other repositories
