### ISSUE TITLE
Skipping installed packages with different tags

### ISSUE THREAD

**Issue by HuidaeCho** [sbopkg/sbopkg#89]
First of all, thanks for the great script!

I have a question or maybe a request. Is there any way to skip (`-k`) packages installed with different tags (e.g., `_1ponce`)? Currently, sbopkg doesn't seem to recognize those packages with a different tag.

Thanks!

**Comment by willysr** [comment]
yes, it's designed to handle _SBo tag only since it only supports for official SBo packages
third party repository outside of SBo is encouraged to use different tag as mentioned in the FAQ https://slackbuilds.org/faq/#package_repos
