### ISSUE TITLE
sqg loops indefinitely over the processing of the `ttfautohint-py` queue

### ISSUE THREAD

**Issue by downwater** [sbopkg/sbopkg#90]
Dear all,

I just synchronized `sbopkg` with the remote repository, and then ran sqg -a. However, it seems to never complete the processing of  `ttfautohint-py` queue.

Steps to reproduce:

1. Run `sbopkg`
2. From the menu, synchronize with the remote repository and wait for it
3. Run `sqg -a` and in another terminal
4. Wait til it seems the output display the report looking like the output below:
`The system ETA: [time in seconds] Left: 8173 AVG [time in seconds] local: 1/722/100%/[time in seconds]`

Executing the command below to check the last file generated in the queues directory will produce output looking like the following:
```
$ cd /path/to/the/queue/directory
$ find . -printf "%T+\t%p\n" | sort | tail
2023-07-24+13:22:12.0391218250  ./python3-qbittorrent-api.sqf
2023-07-24+13:22:12.0821207000  ./python3-babel.sqf
2023-07-24+13:22:12.1781181890  ./python3-booleanOperations.sqf
2023-07-24+13:22:12.2961151030  ./django-debug-toolbar.sqf
2023-07-24+13:22:12.5251091140  ./python3-Flask-Dance.sqf
2023-07-24+13:22:12.6501058450  ./python3-kodipydent.sqf
2023-07-24+13:22:12.7751025750  ./python3-automat.sqf
2023-07-24+13:22:12.9350983910  ./python3-prompt_toolkit.sqf
2023-07-24+13:22:13.0100964290  ./asttokens.sqf
2023-07-24+13:32:28.0500102320  ./ttfautohint-py.sqf.tmp
```

ttfautohint-py.sqf.tmp is continuously modifed at this step (lines are removed, other are added).

Issue reproduced on Slackware 64 15.0, up-to-date with `sbopkg` 0.38.2.

**Comment by willysr** [comment]
this also applies to  python3-ufolib2, afdko, Type1_to_OTF

**Comment by willysr** [comment]
there's a circular loop, python-fonttools -> python-fonttools -> python-fonttools
once we break those loop, the sqg tool will resume normally

**Comment by willysr** [comment]
should be fixed with this commit https://git.slackbuilds.org/slackbuilds/commit/?id=312777077

**Comment by downwater** [comment]
I manually removed the culprit dependency according to the commit, and `sqg` completed indeed the generation.

**Comment by willysr** [comment]
Thanks for clarifying. I will mark this issue closed as this is an issue in SBo rather than sbopkg
